# Generated by Django 3.0.7 on 2020-06-30 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_site_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('-created_at',)},
        ),
    ]
